server:
  port: 8080

# spring基础配置
spring:
  datasource:
    url: jdbc:mysql://192.168.154.128:3306/lucky_dog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mhb19940803751X
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 192.168.154.128
    port: 6379
    password: 12345678
    timeout: 5000ms
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  http:
    servlet:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 100Mb
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: entity # 注意：对应实体类的路径

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: http://169.254.197.129
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: 169.254.197.129:22122


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: truefdfs.resHost
  support-methods-arguments: true
  params: count=countSql

# 小程序配置
app:
  appId: wx1ba1d504c0635c65
  appSecret: f936af5ebc7f6f95c0c0d7e673fe43c1
  url: https://api.weixin.qq.com/sns/jscode2session?grant_type=authorization_code&

robot:
  userId: 404363
  apikey: beb61eac21cb4cc5a9452f3cafd6f481
  url: http://openapi.tuling123.com/openapi/api/v2

urlList: https://qiniu.luckydogma.work/animation_1.mp4,
  https://qiniu.luckydogma.work/film_1.mp4,
  https://qiniu.luckydogma.work/animation_2.mp4,
  https://qiniu.luckydogma.work/film_2.mp4,
  https://qiniu.luckydogma.work/animation_3.mp4,
  https://qiniu.luckydogma.work/film_3.mp4

publicApi:
  # 周公解梦
  dream_url: http://v.juhe.cn/dream/query?q={q}&full={full}&key={key}
  dream_key: 046d4abded5a07831e13498020bb95b4
  # 老黄历
  laohuangli_url: http://v.juhe.cn/laohuangli/d?date={date}&key={key}
  laohuangli_key: 73267601cde9eaf4d3308d12f5f0034f

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
#    healthcheck:
#      enabled: true
