server:
  port: 8085

# spring基础配置
spring:
  application:
    name: luckySite
  datasource:
    url: jdbc:mysql://192.168.154.138:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mhb19940803751X
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: mhb19940803751X
    timeout: 5000ms
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  http:
    servlet:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 100Mb
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: entity # 注意：对应实体类的路径

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: 127.0.0.1:22122
  resHost:


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: truefdfs.resHost
  support-methods-arguments: true
  params: count=countSql

urlList:

robot:
  userId:
  apikey:
  url:

app:
  appId:
  appSecret:
  url:

publicApi:
  url: http://v.juhe.cn/dream/query
  key: 046d4abded5a07831e13498020bb95b4

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
#    healthcheck:
#      enabled: true
