server:
  port: 8080

# spring基础配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lucky_site
    username: root
    password: mhb19940803751X
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 169.254.197.129
    port: 6379
    password: 12345678
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: entity # 注意：对应实体类的路径

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 169.254.197.129
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: 169.254.197.129:22122


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 小程序配置




